<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__dy-lb-close</name>
   <tag></tag>
   <elementGuidId>afd09d94-e3d6-458a-a843-d6d19533fd89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'dy-lb-close']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dy-lb-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wf-barlow-n2-active wf-barlow-n4-active wf-barlow-n7-active wf-active&quot;]/body[1]/div[@class=&quot;dy-modal-container dy-act-overlay&quot;]/div[@class=&quot;dy-modal-wrapper&quot;]/div[@class=&quot;dy-modal-contents&quot;]/div[@class=&quot;dy-lb-close&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
